"""empty message

Revision ID: 19999cbf037f
Revises: a54d6251d4a0
Create Date: 2025-12-23 20:26:57.983973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19999cbf037f'
down_revision = 'a54d6251d4a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=True)

    # ### end Alembic commands ###
